import type { Metadata } from 'next'

import Header from '@/components/header/header'
import Providers from '@/store/providers'
import { cn } from '@/utils'

import { raleway } from './fonts'
import './globals.css'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('flex min-h-screen flex-col', raleway.className)}>
        <Providers>
          <Header />
          <main className="flex-shrink flex-grow basis-0">{children}</main>
          <div>11111</div>
        </Providers>
      </body>
    </html>
  )
}
