import type { Metadata } from 'next'

import Header from '@/components/header/header'
import Providers from '@/store/providers'
import { classnames } from '@/utils'

import { raleway } from './fonts'
import './globals.css'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={classnames('min-h-screen flex flex-col', raleway.className)}
      >
        <Providers>
          <Header />
          <main className="flex-grow flex-shrink basis-0">{children}</main>
          <div>11111</div>
        </Providers>
      </body>
    </html>
  )
}
